import { writeFileSync } from 'fs';

import { transform } from './transform';

// Mock out FS to avoid writing to disk
// We aren't processing the result anyway, so no need for specifying the response
jest.mock('fs');

describe('babel-plugin-strip-runtime with stylesheet extraction (extractStylesToDirectory)', () => {
  describe('with the classic runtime', () => {
    const runtime = 'classic';

    describe('without JSX pragma', () => {
      const code = `
        import '@compiled/react';

        const Component = () => (
          <div css={{ fontSize: 12, color: 'blue' }}>
            hello world
          </div>
        );
      `;

      it('adds styles to directory', () => {
        const actual = transform(code, {
          run: 'both',
          runtime,
          extractStylesToDirectory: { source: 'src/', dest: 'dist/' },
        });

        expect(actual).toMatchInlineSnapshot(`
          "/* app.tsx generated by @compiled/babel-plugin v0.0.0 */
          import './app.compiled.css';
          import * as React from 'react';
          import { ax, ix } from '@compiled/react/runtime';
          const Component = () =>
            /*#__PURE__*/ React.createElement(
              'div',
              {
                className: ax(['_1wyb1fwx _syaz13q2']),
              },
              'hello world'
            );
          "
        `);

        expect(writeFileSync).toBeCalledWith(
          expect.stringContaining('app.compiled.css'),
          '._1wyb1fwx{font-size:12px}\n._syaz13q2{color:blue}'
        );
      });

      it('error when source directory is not found', () => {
        expect(() =>
          transform(code, {
            run: 'both',
            runtime,
            extractStylesToDirectory: { source: 'not-existing-src/', dest: 'dist/' },
          })
        ).toThrowWithMessage(
          Error,
          `/base/src/app.tsx: Source directory 'not-existing-src/' was not found relative to source file ('../src/app.tsx')`
        );
      });
    });

    describe('with JSX pragma', () => {
      it('extracts styles into app.compiled.css', () => {
        const codeWithPragma = `
          /** @jsx myJsx */
          import { css, jsx as myJsx } from '@compiled/react';

          const Component = () => (
            <div css={{ fontSize: 12, color: 'blue' }}>
              hello world 2
            </div>
          );

          const Component2 = () => (
            <div css={css({ fontSize: 12, color: 'pink' })}>
              hello world 2
            </div>
          );
        `;

        const actual = transform(codeWithPragma, {
          run: 'both',
          runtime: 'classic',
          extractStylesToDirectory: { source: 'src/', dest: 'dist/' },
        });

        expect(actual).toMatchInlineSnapshot(`
          "/* app.tsx generated by @compiled/babel-plugin v0.0.0 */
          import './app.compiled.css';
          import * as React from 'react';
          import { ax, ix } from '@compiled/react/runtime';
          const Component = () =>
            /*#__PURE__*/ React.createElement(
              'div',
              {
                className: ax(['_1wyb1fwx _syaz13q2']),
              },
              'hello world 2'
            );
          const Component2 = () =>
            /*#__PURE__*/ React.createElement(
              'div',
              {
                className: ax(['_1wyb1fwx _syaz32ev']),
              },
              'hello world 2'
            );
          "
        `);
      });
    });
  });

  describe('with the automatic runtime', () => {
    describe('with JSX pragma', () => {
      it('extracts styles into app.compiled.css', () => {
        const codeWithPragma = `
          /** @jsxImportSource @compiled/react */
          import { css } from '@compiled/react';

          const Component = () => (
            <div css={{ fontSize: 12, color: 'blue' }}>
              hello world 2
            </div>
          );

          const Component2 = () => (
            <div css={css({ fontSize: 12, color: 'pink' })}>
              hello world 2
            </div>
          );
        `;

        const actual = transform(codeWithPragma, {
          run: 'both',
          runtime: 'automatic',
          extractStylesToDirectory: { source: 'src/', dest: 'dist/' },
        });

        expect(actual).toMatchInlineSnapshot(`
          "/* app.tsx generated by @compiled/babel-plugin v0.0.0 */
          import './app.compiled.css';
          import { ax, ix } from '@compiled/react/runtime';
          import { jsxs as _jsxs, jsx as _jsx } from 'react/jsx-runtime';
          const Component = () =>
            /*#__PURE__*/ _jsx('div', {
              className: ax(['_1wyb1fwx _syaz13q2']),
              children: 'hello world 2',
            });
          const Component2 = () =>
            /*#__PURE__*/ _jsx('div', {
              className: ax(['_1wyb1fwx _syaz32ev']),
              children: 'hello world 2',
            });
          "
        `);
      });
    });
  });

  describe('with @compiled/vanilla', () => {
    // Vanilla input has no JSX, so the JSX runtime choice (classic vs.
    // automatic) doesn't change the emitted output. We use the modern
    // automatic runtime because it's the default for new code.
    const runtime = 'automatic';

    it('extracts cssMap styles and merges variants with ax — realistic ProseMirror-style use', () => {
      // Simulates a typical non-React consumer (e.g. a ProseMirror node
      // view's `toDOM` helper): declare a style map with a base variant
      // plus a couple of conditional variants, then merge selected
      // variants together with `ax` to compute the final className.
      const code = `
        import { cssMap, ax } from '@compiled/vanilla';

        const styles = cssMap({
          base: {
            display: 'inline-block',
            paddingInline: 8,
            color: 'currentColor',
          },
          primary: {
            color: 'white',
            backgroundColor: 'blue',
          },
          danger: {
            color: 'white',
            backgroundColor: 'red',
          },
        });

        export function buildBadgeClassName(variant) {
          return ax([
            styles.base,
            variant === 'primary' && styles.primary,
            variant === 'danger' && styles.danger,
          ]);
        }
      `;

      const actual = transform(code, {
        run: 'both',
        runtime,
        extractStylesToDirectory: { source: 'src/', dest: 'dist/' },
      });

      // Bundle output expectations:
      //
      // - The className map is a plain object literal. Each variant's value
      //   is the *space-separated atomic className* the user will compose
      //   via `ax([...])` at runtime — this is the contract between
      //   `cssMap` and `ax`.
      //
      // - The sibling `import './app.compiled.css'` is the sentinel the
      //   bundler picks up (via the `sideEffects: ['**/*.compiled.css']`
      //   package convention) to serve the extracted styles.
      //
      // - The user's original `import { cssMap, ax } from '@compiled/vanilla'`
      //   is fully consumed: `cssMap` was rewritten to a plain object literal,
      //   and `ax` was rewritten to come from `@compiled/vanilla/runtime`.
      //   The `@compiled/vanilla` package entry never appears in the bundle.
      //
      // - `insertSheets` is gone (extracted), as is any React import.
      expect(actual).toMatchInlineSnapshot(`
        "/* app.tsx generated by @compiled/babel-plugin v0.0.0 */
        import './app.compiled.css';
        import { ax } from '@compiled/vanilla/runtime';
        const styles = {
          base: '_18zrftgi _1e0c1o8l _syaz1r31',
          primary: '_syaz1x77 _bfhk13q2',
          danger: '_syaz1x77 _bfhk5scu',
        };
        export function buildBadgeClassName(variant) {
          return ax([
            styles.base,
            variant === 'primary' && styles.primary,
            variant === 'danger' && styles.danger,
          ]);
        }
        "
      `);

      // Extracted stylesheet expectations:
      //
      // The CSS file written to `dist/app.compiled.css` must contain one
      // atomic rule per declaration in the source `cssMap`, with the same
      // hash class names that appear in the JS bundle's className map
      // above. That coupling is what makes `ax([styles.base])` resolve to
      // a real visual style at runtime.
      //
      // - `paddingInline: 8` is emitted as a single `padding-inline:8px`
      //   rule. Compiled does not split logical-property shorthands into
      //   physical pairs because all evergreen browsers support
      //   `padding-inline` natively.
      //
      // - `color: 'white'` is shared between the `primary` and `danger`
      //   variants and dedupes to a single atomic rule (`_syaz1x77`) that
      //   both className strings reference. This is the byte-saving win
      //   atomic CSS exists to deliver.
      //
      // - Rule order in the extracted file follows the bucket-sorted order
      //   produced by the CSS pipeline (`sort-atomic-style-sheet.ts`),
      //   not the source-code order of the input `cssMap`.
      expect(writeFileSync).toHaveBeenLastCalledWith(
        expect.stringContaining('app.compiled.css'),
        [
          '._18zrftgi{padding-inline:8px}',
          '._1e0c1o8l{display:inline-block}',
          '._bfhk13q2{background-color:blue}',
          '._bfhk5scu{background-color:red}',
          '._syaz1r31{color:currentColor}',
          '._syaz1x77{color:white}',
        ].join('\n')
      );
    });
  });
});
