[package]
name = "swc-plugin-compiled"
version = "0.1.0"
edition = "2021"
homepage = "https://github.com/atlassian-labs/compiled"
license  = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
swc_core = { version = "34.0.*", features = ["ecma_plugin_transform", "ecma_ast", "common", "ecma_utils", "ecma_visit"] }
once_cell = "1"
regex = "1"
sourcemap = "7"
base64 = "0.21"
radix_fmt = "1"
fxhash = "0.2"
byteorder = "1"

# .cargo/config.toml defines few alias to build plugin.
# cargo build-wasip1 generates wasm32-wasip1 binary
# cargo build-wasm32 generates wasm32-unknown-unknown binary.
