[package]
name = "compiled-swc"
version = "0.1.0"
edition = "2021"
description = "A SWC implementation of the Compiled CSS-in-JS library"
license = "Apache-2.0"

[package.metadata.swc]
plugin = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
swc_core = { version = "0.96", features = [
  "ecma_plugin_transform",
  "ecma_utils",
  "ecma_visit",
  "ecma_codegen",
  "__parser",
  "ecma_parser",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
path-clean = "1.0"
pathdiff = "0.2"
regex = "1.10"

# WASI target automatically supports getrandom
# No special dependencies needed for wasm32-wasip1

[dev-dependencies]
swc_core = { version = "0.96", features = [
  "testing_transform",
  "__parser",
  "ecma_parser",
  "ecma_codegen",
] }

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"