[package]
name     = "swc_plugin_compiled"
version  = "0.1.0"
edition  = "2024"
homepage = "https://github.com/atlassian-labs/compiled"
license  = "Apache-2.0"

[dependencies]
swc_core = ">=15.0.0, <27.0.0"
