import { bundle } from './utils/webpack';

describe('extract webpack plugin', () => {
  it('should do something', async () => {
    const result = await bundle`
      import '@compiled/react';
      import { hydrate } from 'react-dom';

      const App = () => <div css={{ fontSize: 20 }}>hello world</div>;

      hydrate(<App />, document.getElementById('app'));
    `;

    expect(result).toMatchInlineSnapshot(`
      "(self[\\"webpackChunkcompiled\\"] = self[\\"webpackChunkcompiled\\"] || []).push([[\\"main\\"],{

      /***/ 618:
      /***/ ((__unused_webpack_module, __unused_webpack___webpack_exports__, __webpack_require__) => {

      \\"use strict\\";
      /* harmony import */ var react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(823);
      /* harmony import */ var _compiled_react_runtime__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(931);
      /* harmony import */ var _compiled_react_runtime__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(734);
      /* harmony import */ var _compiled_react_runtime__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(887);
      /* harmony import */ var react_dom__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(116);
      /* compiled-test.js generated by @compiled/babel-plugin v0.0.0 */





      const _ = \\"._1wybgktf{font-size:20px}\\";

      const App = () => /*#__PURE__*/(0,react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsxs)(_compiled_react_runtime__WEBPACK_IMPORTED_MODULE_2__/* .default */ .Z, {
        children: [/*#__PURE__*/(0,react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)(_compiled_react_runtime__WEBPACK_IMPORTED_MODULE_3__/* .default */ .Z, {
          nonce: \\"k0Mp1lEd\\",
          children: [_]
        }), /*#__PURE__*/(0,react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)(\\"div\\", {
          className: (0,_compiled_react_runtime__WEBPACK_IMPORTED_MODULE_4__/* .default */ .Z)([\\"_1wybgktf\\"]),
          children: \\"hello world\\"
        })]
      });

      (0,react_dom__WEBPACK_IMPORTED_MODULE_1__.hydrate)( /*#__PURE__*/(0,react_jsx_runtime__WEBPACK_IMPORTED_MODULE_0__.jsx)(App, {}), document.getElementById('app'));

      /***/ })

      },
      0,[[618,\\"runtime~main\\",\\"vendor\\"]]]);"
    `);
  }, 10000);
});
