import { transformSync } from '@babel/core';
import babelPlugin from '../../index';

const transform = (code: TemplateStringsArray) => {
  return transformSync(code[0], {
    configFile: false,
    babelrc: false,
    plugins: [babelPlugin],
  })?.code;
};

describe('global component transform', () => {
  it('should transform global component', () => {
    const actual = transform`
      import { Global } from '@compiled/react';

      <Global styles={{ fontSize: 20 }} />
    `;

    expect(actual).toMatchInlineSnapshot(`
      "/* File generated by @compiled/babel-plugin v0.0.0 */

      import * as React from 'react';
      import { ax, ix, CC, CS } from \\"@compiled/react/runtime\\";
      <Global styles={{
        fontSize: 20
      }} />;"
    `);
  });

  it('should replace the global component with null if there is no style prop', () => {
    const actual = transform`
      import { Global } from '@compiled/react';

      <Global />
    `;

    expect(actual).toMatchInlineSnapshot(`
      "/* File generated by @compiled/babel-plugin v0.0.0 */

      import * as React from 'react';
      import { ax, ix, CC, CS } from \\"@compiled/react/runtime\\";
      null;"
    `);
  });

  it('should replace the global component with null if there are no defined styles', () => {
    const actual = transform`
      import { Global } from '@compiled/react';

      <Global styles={{}} />
    `;

    expect(actual).toMatchInlineSnapshot(`
      "/* File generated by @compiled/babel-plugin v0.0.0 */

      import * as React from 'react';
      import { ax, ix, CC, CS } from \\"@compiled/react/runtime\\";
      null;"
    `);
  });
});
