[build]
  base = "/website/"
  publish = "dist/"
  command = "yarn build"

[[redirects]]
  from = "/docs/*"
  to = "/docs/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
