[build]
  base = "/"
  publish = "dist/"
  command = "yarn build"
  environment = { YARN_VERSION = "1.9.4" }

[[redirects]]
  from = "/docs/*"
  to = "/docs/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
