name: Task Checklist
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: yarn install
    - name: Check tasks in PR description
      run: yarn run check-tasks
