name: Run task checklist

on:
  check_run:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  task-checklist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/task-checklist/
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
